version: "3.8"

services:
 frontend:
  build:
   context: ./frontend
   dockerfile: Dockerfile
  ports:
   - "3000:3000" # Viteのデフォルトポート
  volumes:
   - ./frontend:/app # ソースコードの同期
   - /app/node_modules # node_modulesが上書きされないように
  environment:
   - CHOKIDAR_USEPOLLING=true # ホットリロードのため
  depends_on:
   - backend
  networks:
   - refuel_network

 backend:
  build:
   context: ./backend
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  volumes:
   - ./backend:/app # ソースコードの同期
  depends_on:
   db:
    condition: service_healthy
  environment:
   # DB接続情報は適宜変更してください
   - DB_HOST=db
   - DB_PORT=3306
   - DB_USER=refuel_user
   - DB_PASSWORD=refuel_password
   - DB_NAME=refuel_db
  networks:
   - refuel_network

 db:
  image: mysql:8.0
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: root_password
   MYSQL_DATABASE: refuel_db
   MYSQL_USER: refuel_user
   MYSQL_PASSWORD: refuel_password
  volumes:
   - mysql_data:/var/lib/mysql
   # 初期マイグレーションファイルがある場合: - ./backend/migrations:/docker-entrypoint-initdb.d
  healthcheck:
   test:
    [
     "CMD",
     "mysqladmin",
     "ping",
     "-h",
     "localhost",
     "-u",
     "root",
     "-p$$MYSQL_ROOT_PASSWORD",
    ]
   interval: 10s
   timeout: 5s
   retries: 5
  networks:
   - refuel_network

volumes:
 mysql_data:

networks:
 refuel_network:
  driver: bridge
